sudo: false
language: java
jdk: oraclejdk8

script: "./gradlew clean client:test"

deploy:
- provider: script
  script:
  - "gpg --keyring=$TRAVIS_BUILD_DIR/pubring.gpg --no-default-keyring --import signing-key.asc"
  - "./gradlew client:distZip client:publish
    -Pproject.version=$TRAVIS_TAG
    -Psigning.keyId=F60F1153 -Psigning.password=$PASSPHRASE -Psigning.secretKeyRingFile=$TRAVIS_BUILD_DIR/pubring.gpg"
  skip_cleanup: true
  on:
    tags: true
- provider: releases
  api_key: "$GITHUB_KEY"
  file_glob: true
  file: client/build/distributions/*-$TRAVIS_TAG.zip
  skip_cleanup: true
  on:
    tags: true

before_cache:
- rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
- rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
  - "$HOME/.gradle/caches/"
  - "$HOME/.gradle/wrapper/"

dist: trusty

env:
  global:
    secure: jn8u5Uy2Bf9+k+T54/IsXFvpj2eZJBZwEkfkVdQfu2qQ9AHgh9HMNaKuoGmouhYqshCFT57aAGPrCFaa3f+1Wz7IzAlihqt7EGTBFKPCVWa4ZaZMLRKYgGAHKZN1IwwZ8mx37fMSWHRTKNNTMKUs0ftrE/ZFJvu1SZkkti8zbZmQZEF7qzqO3DimO15QvPsCtcXBMdjBzeIRwqjVsUwuocL/c6ymlsMRpYi+TutV7rWoD6sLfIBNdqW04DR9jeceAoAN7nHXEyKaIBTbTOtn8p/1ab+PdpEdt9DihoQWfzCipT7/1FL2/yj1XU9/Eki81zomHCpvPhIcxkl3UCzKu51DYaI3az67meyVyfIXwPZd7JKtD6rV0JU76SDo+bbWfC4PzMM1qFgnlh8w2JVDvBKrY0396noaBNyXu+VF6MRWdW+VP4UnCg0sC0+upKDB0DJ3DGBo3FFuH2o4xpK/6uci6M3iZBqVxZ0Cby0QL0d7LhKdv+SsLOinNCYa0rLYIDWQfLN16fDEiD8DdBpe3YwBKg3YqCNV+2K5nF/sXONqh+oAdbVN81/gYvjNDQldf3mPB2BIgoDsZE0QFXXLioQ0QCnDGRBIBevOw7YKG/LL0m6giuZAfxqTYX9WU3VUiLGv7NT38VAs6erlx9EcMCbJGoCwbp1e+380y2z07Bg=

before_install:
- openssl aes-256-cbc -K $encrypted_167b3928cfdc_key -iv $encrypted_167b3928cfdc_iv
  -in signing-key.asc.enc -out signing-key.asc -d
